apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-demo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: kubernetes-demo
spec:
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11.7
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: db_password
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: kubernetes-demo
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  namespace: kubernetes-demo
spec:
  selector:
    matchLabels:
      app: php-app
  replicas: 2
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: php-app
          image: ghcr.io/mgleska/monolith-with-modules-and-4-layers
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "mysql://root:db_password@database:3306/monolith-app?serverVersion=10.11.7-MariaDB&charset=utf8mb4"
          command: ["/bin/sh", "-c", "/app/start-app.sh"]
---
apiVersion: v1
kind: Service
metadata:
  name: php-app
  namespace: kubernetes-demo
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: php-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: kubernetes-demo
spec:
  rules:
    - host: "kubernetes.local"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: php-app
                port:
                  number: 8000
